#!/bin/zsh

export ZSH_AUTOSUGGEST_STRATEGY=(history completion)
export HISTFILE=~/.cache/zsh_history
export HISTSIZE=8192
export SAVEHIST=8192
export PROMPT="%~ "

# This is required for PATH completion
autoload compinit && compinit

source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh 
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh 

